using Devbeat.DTE.JsonToCSharp.Represesentation;

namespace Devbeat.DTE.JsonToCSharp.Writers;

internal sealed class CSharpWriter
{
    private static string NEWLINE => Environment.NewLine;
    private bool _hasWrittenProperty = false;

    internal static CSharpWriter CreateNew()
    {
        return new CSharpWriter();
    }

    internal string Write(
        CSharpCode codeRepresentation
        , CSharpWriteOptions? options = null)
    {
        var sb = new StringBuilder();
        using var writer = new StringWriter(sb);

        options ??= CSharpWriteOptions.Default;

        WriteNamespace(writer, codeRepresentation.Namespace);

        foreach (var classObject in codeRepresentation.Classes)
        {
            WriteBeginClass(writer, classObject.Name, classObject is CSharpRecord);

            foreach (var propertyObject in classObject.Properties)
            {
                WriteProperty(
                    writer
                    , propertyObject.Type
                    , propertyObject.Name
                    , propertyObject.IsCollection
                    , propertyObject.IsNullable
                    , classObject is CSharpRecord);
            }

            WriteEndClass(writer, classObject is CSharpRecord);
        }

        return sb.ToString();
    }

    private void WriteProperty(
        StringWriter writer, string type, string name, bool isCollection, bool isNullable, bool writeByRecord)
    {
        if (writeByRecord)
        {
            if (_hasWrittenProperty)
            {
                writer.Write($",{NEWLINE}");
            }
            writer.Write(
                $"\t{type}{(isNullable ? "?" : "")}{(isCollection ? "[]" : "")} {name}");
        }
        else
        {
            writer.WriteLine(
                $"\tpublic {type}{(isNullable ? "?" : "")}{(isCollection ? "[]" : "")} {name} {{ get; set; }}");
        }
        _hasWrittenProperty = true;
    }

    private void WriteBeginClass(StringWriter writer, string name, bool writeAsRecord)
    {
        if (writeAsRecord)
        {
            writer.WriteLine($"{NEWLINE}public record {name}(");
        }
        else 
        {
            writer.WriteLine($"{NEWLINE}public class {name}{NEWLINE}{{");
        } 
    }

    private void WriteEndClass(StringWriter writer, bool writeAsRecord)
    {
        writer.WriteLine(writeAsRecord ? $"{NEWLINE});" : "}");
    }

    private void WriteNamespace(StringWriter writer, string name)
    {
        writer.WriteLine($"// auto-generated by Devbeat JsonToCSharp for DevToys{NEWLINE}{NEWLINE}namespace {name};");
    }
}
